In [1]:
import numpy as np

In [3]:
l=[1,2,4,5]

In [4]:
arr=np.array(l)

In [5]:
arr

array([1, 2, 4, 5])

In [5]:
arr1=np.matrix(l)

In [6]:
arr1

matrix([[1, 2, 4, 5]])

In [7]:
a=np.array([1,4,6])

In [8]:
a

array([1, 4, 6])

In [10]:
b=a

In [11]:
b

array([1, 4, 6])

In [12]:
b[0]=20

In [13]:
b

array([20,  4,  6])

In [14]:
a

array([20,  4,  6])

In [15]:
a[2]=399

In [17]:
a

array([ 20,   4, 399])

In [19]:
b

array([ 20,   4, 399])

In [20]:
c=np.copy(a)

In [21]:
c

array([ 20,   4, 399])

In [22]:
c[1]=12

In [23]:
c

array([ 20,  12, 399])

In [24]:
a

array([ 20,   4, 399])

In [26]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [27]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [28]:
np.fromfunction(lambda i,j:i+j,(3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [29]:
np.fromfunction(lambda i,j:i-j,(3,3))

array([[ 0., -1., -2.],
       [ 1.,  0., -1.],
       [ 2.,  1.,  0.]])

In [31]:
np.fromfunction(lambda i,j:i**2+j,(3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [4., 5., 6.]])

In [32]:
# Data type

In [33]:
l=[1,2,3,4,5]

In [34]:
m=np.array(l)

In [35]:
m

array([1, 2, 3, 4, 5])

In [36]:
m.ndim

1

In [37]:
n=np.array([[1,2,3,4],[5,3,4,2]])

In [38]:
n

array([[1, 2, 3, 4],
       [5, 3, 4, 2]])

In [39]:
n.ndim

2

In [40]:
m.size

5

In [41]:
n.size

8

In [42]:
m.shape

(5,)

In [43]:
n.shape

(2, 4)

In [44]:
np.arange(2.2,4.5)

array([2.2, 3.2, 4.2])

In [45]:
np.zeros(3)

array([0., 0., 0.])

In [47]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [48]:
np.zeros((3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [55]:
q=np.ones((3,2,3))

In [56]:
q

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [57]:
q+3

array([[[4., 4., 4.],
        [4., 4., 4.]],

       [[4., 4., 4.],
        [4., 4., 4.]],

       [[4., 4., 4.],
        [4., 4., 4.]]])

In [59]:
q*5

array([[[5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.]]])

In [63]:
np.empty((4,5))

array([[4.66309238e-310, 0.00000000e+000, 6.91313415e-310,
        6.91313415e-310, 6.91313415e-310],
       [6.91313415e-310, 6.91313415e-310, 6.91313415e-310,
        6.91313415e-310, 6.91361584e-310],
       [6.91361750e-310, 6.91361753e-310, 6.91361752e-310,
        6.91361750e-310, 6.91361752e-310],
       [6.91361745e-310, 6.91361749e-310, 6.91361749e-310,
        6.91361749e-310, 6.91361749e-310]])

In [66]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
np.linspace(2,5,15)

array([2.        , 2.21428571, 2.42857143, 2.64285714, 2.85714286,
       3.07142857, 3.28571429, 3.5       , 3.71428571, 3.92857143,
       4.14285714, 4.35714286, 4.57142857, 4.78571429, 5.        ])

In [69]:
#Log function
np.logspace(2,5,12)

array([   100.        ,    187.38174229,    351.11917342,    657.93322466,
         1232.84673944,   2310.12970008,   4328.76128108,   8111.3083079 ,
        15199.11082953,  28480.35868436,  53366.99231206, 100000.        ])

In [70]:
np.logspace(2,5,12,base=2)

array([ 4.        ,  4.83235778,  5.83792042,  7.05273004,  8.52032872,
       10.29331918, 12.43525025, 15.02289457, 18.14900036, 21.92561576,
       26.48810496, 32.        ])

In [6]:
w=np.random.randn(3,4)

In [7]:
import pandas as pd

In [8]:
pd.DataFrame(w)

0         1         2         3
0  0.381056 -0.816405  1.964175 -0.632866
1  0.281155 -1.369276 -0.262656 -0.483586
2  0.792773  0.059477  0.104753 -2.085720

In [14]:
w.reshape(3,4)

array([[ 0.38105646, -0.81640481,  1.96417481, -0.63286576],
       [ 0.28115471, -1.36927649, -0.26265624, -0.48358575],
       [ 0.79277277,  0.05947663,  0.1047534 , -2.08572032]])

In [15]:
w[1][2]

-0.2626562358532364

In [16]:
arr=np.random.randint(2,150,(5,5))

In [17]:
arr

array([[  7, 107,   4, 145, 110],
       [142, 131, 146,  75,  19],
       [ 94, 107,  23,  11,   6],
       [147,  10, 139, 112,  73],
       [135,  49,  49, 130, 124]])

In [18]:
arr>70

array([[False,  True, False,  True,  True],
       [ True,  True,  True,  True, False],
       [ True,  True, False, False, False],
       [ True, False,  True,  True,  True],
       [ True, False, False,  True,  True]])

In [21]:
arr[arr>70]

array([107, 145, 110, 142, 131, 146,  75,  94, 107, 147, 139, 112,  73,
       135, 130, 124])

In [22]:
arr

array([[  7, 107,   4, 145, 110],
       [142, 131, 146,  75,  19],
       [ 94, 107,  23,  11,   6],
       [147,  10, 139, 112,  73],
       [135,  49,  49, 130, 124]])

In [23]:
arr[2:4,[2,3]]

array([[ 23,  11],
       [139, 112]])

In [66]:
#Mathematics functions or Binary operation

In [25]:
x=np.random.randint(1,4,(3,3))
y=np.random.randint(1,4,(3,3))


In [26]:
x

array([[3, 3, 1],
       [1, 1, 1],
       [1, 1, 2]])

In [27]:
y

array([[1, 3, 3],
       [2, 2, 2],
       [2, 1, 2]])

In [28]:
x+y

array([[4, 6, 4],
       [3, 3, 3],
       [3, 2, 4]])

In [29]:
x-y

array([[ 2,  0, -2],
       [-1, -1, -1],
       [-1,  0,  0]])

In [30]:
x/y

array([[3.        , 1.        , 0.33333333],
       [0.5       , 0.5       , 0.5       ],
       [0.5       , 1.        , 1.        ]])

In [31]:
x*y

array([[3, 9, 3],
       [2, 2, 2],
       [2, 1, 4]])

In [67]:
x%y

array([[0, 0, 1],
       [1, 1, 1],
       [1, 0, 0]])

In [68]:
x**y

array([[ 3, 27,  1],
       [ 1,  1,  1],
       [ 1,  1,  4]])

In [69]:
x&y

array([[1, 3, 1],
       [0, 0, 0],
       [0, 1, 2]])

In [70]:
~x

array([[-4, -4, -2],
       [-2, -2, -2],
       [-2, -2, -3]])

In [71]:
x|y

array([[3, 3, 3],
       [3, 3, 3],
       [3, 1, 2]])

In [32]:
#matrix multiplication
x@y

array([[11, 16, 17],
       [ 5,  6,  7],
       [ 7,  7,  9]])

In [33]:
#Brodcasting numpy

In [35]:
v=np.zeros((4,4))

In [36]:
v

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
p=np.array([1,3,5,7])

In [38]:
p

array([1, 3, 5, 7])

In [40]:
l=v+p

In [41]:
l

array([[1., 3., 5., 7.],
       [1., 3., 5., 7.],
       [1., 3., 5., 7.],
       [1., 3., 5., 7.]])

In [42]:
np.sqrt(l)

array([[1.        , 1.73205081, 2.23606798, 2.64575131],
       [1.        , 1.73205081, 2.23606798, 2.64575131],
       [1.        , 1.73205081, 2.23606798, 2.64575131],
       [1.        , 1.73205081, 2.23606798, 2.64575131]])

In [43]:
np.log10(l)

array([[0.        , 0.47712125, 0.69897   , 0.84509804],
       [0.        , 0.47712125, 0.69897   , 0.84509804],
       [0.        , 0.47712125, 0.69897   , 0.84509804],
       [0.        , 0.47712125, 0.69897   , 0.84509804]])

In [44]:
np.exp(l)

array([[   2.71828183,   20.08553692,  148.4131591 , 1096.63315843],
       [   2.71828183,   20.08553692,  148.4131591 , 1096.63315843],
       [   2.71828183,   20.08553692,  148.4131591 , 1096.63315843],
       [   2.71828183,   20.08553692,  148.4131591 , 1096.63315843]])

In [45]:
#Array Manupulation

In [46]:
arr=np.random.randint(4,14,(3,4))

In [47]:
arr

array([[ 5, 12,  9,  4],
       [11, 12,  7, 13],
       [ 5,  5,  4,  7]])

In [48]:
arr.reshape(2,6)

array([[ 5, 12,  9,  4, 11, 12],
       [ 7, 13,  5,  5,  4,  7]])

In [49]:
arr.reshape(6,2)

array([[ 5, 12],
       [ 9,  4],
       [11, 12],
       [ 7, 13],
       [ 5,  5],
       [ 4,  7]])

In [50]:
arr.T

array([[ 5, 11,  5],
       [12, 12,  5],
       [ 9,  7,  4],
       [ 4, 13,  7]])

In [51]:
arr.flatten()

array([ 5, 12,  9,  4, 11, 12,  7, 13,  5,  5,  4,  7])

In [52]:
#expand dimentions1D to 2D
arr1=np.array([5,9,8,3,8])

In [53]:
arr1

array([5, 9, 8, 3, 8])

In [55]:
np.expand_dims(arr1,axis=1)

array([[5],
       [9],
       [8],
       [3],
       [8]])

In [56]:
np.expand_dims(arr1,axis=0)

array([[5, 9, 8, 3, 8]])

In [57]:
np.squeeze(arr)

array([[ 5, 12,  9,  4],
       [11, 12,  7, 13],
       [ 5,  5,  4,  7]])

In [59]:
w=np.array([[1],[4],[5]])

In [60]:
w

array([[1],
       [4],
       [5]])

In [61]:
np.squeeze(w)

array([1, 4, 5])

In [62]:
np.repeat(w,2)

array([1, 1, 4, 4, 5, 5])

In [65]:
np.roll(w,3)

array([[1],
       [4],
       [5]])

In [72]:
#String operation

In [73]:
arr1=np.array(['vinit','kumar','chauhan'])

In [74]:
arr1

array(['vinit', 'kumar', 'chauhan'], dtype='<U7')

In [75]:
np.char.upper(arr1)

array(['VINIT', 'KUMAR', 'CHAUHAN'], dtype='<U7')

In [76]:
np.char.title(arr1)

array(['Vinit', 'Kumar', 'Chauhan'], dtype='<U7')

In [79]:
np.char.capitalize(arr1)

array(['Vinit', 'Kumar', 'Chauhan'], dtype='<U7')

In [81]:
# Trignometric function

In [82]:
b=np.random.randint(1,4,(3,3))

In [83]:
b

array([[2, 1, 2],
       [3, 3, 3],
       [1, 1, 2]])

In [84]:
np.sin(b)

array([[0.90929743, 0.84147098, 0.90929743],
       [0.14112001, 0.14112001, 0.14112001],
       [0.84147098, 0.84147098, 0.90929743]])

In [85]:
np.cos(b)

array([[-0.41614684,  0.54030231, -0.41614684],
       [-0.9899925 , -0.9899925 , -0.9899925 ],
       [ 0.54030231,  0.54030231, -0.41614684]])

In [86]:
np.tan(b)

array([[-2.18503986,  1.55740772, -2.18503986],
       [-0.14254654, -0.14254654, -0.14254654],
       [ 1.55740772,  1.55740772, -2.18503986]])

In [87]:
np.tanh(b)

array([[0.96402758, 0.76159416, 0.96402758],
       [0.99505475, 0.99505475, 0.99505475],
       [0.76159416, 0.76159416, 0.96402758]])

In [89]:
np.power(b,3)

array([[ 8,  1,  8],
       [27, 27, 27],
       [ 1,  1,  8]])

In [90]:
np.mean(b)

2.0

In [91]:
np.median(b)

2.0

In [92]:
np.std(b)

0.816496580927726

In [93]:
np.var(b)

0.6666666666666666

In [94]:
#short,search and counting

In [95]:
arr2=np.array([2,4,6,3,1,7,9,66,44,87,34,56,86,88,456,234,12,33])

In [96]:
arr2

array([  2,   4,   6,   3,   1,   7,   9,  66,  44,  87,  34,  56,  86,
        88, 456, 234,  12,  33])

In [99]:
np.sort(arr2)

array([  1,   2,   3,   4,   6,   7,   9,  12,  33,  34,  44,  56,  66,
        86,  87,  88, 234, 456])

In [100]:
np.searchsorted(arr2,32)

7

In [103]:
np.where(arr2>45)

(array([ 7,  9, 11, 12, 13, 14, 15]),)

In [105]:
np.extract(arr2>45,arr2)

array([ 66,  87,  56,  86,  88, 456, 234])